In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np


In [2]:
def read_csv_method(file_path):
    df = pd.read_csv(file_path)
    sentence = np.array( df["sentence"] ) # X
    label = np.array( df["label"] , dtype=int) # Y
    return sentence , label

In [3]:
X_train , Y_train = read_csv_method("train.csv")
X_test , Y_test = read_csv_method("test.csv")


In [4]:
X_train

array(['never talk to me again', 'I am proud of your achievements',
       'It is the worst day in my life', 'Miss you so much',
       'food is life', 'I love you mum', 'Stop saying bullshit',
       'congratulations on your acceptance',
       'The assignment is too long ', 'I want to go play',
       'she did not answer my text ', 'Your stupidity has no limit',
       'how many points did he score', 'my algorithm performs poorly',
       'I got approved', 'Stop shouting at me',
       'Sounds like a fun plan ha ha', 'no one likes him',
       'the game just finished', 'I will celebrate soon',
       'So sad you are not coming', 'She is my dearest love', 'Good job',
       'It was funny lol', 'candy is life ', 'The chicago cubs won again',
       'I am hungry', 'I am so excited to see you after so long',
       'you did well on you exam', 'lets brunch some day',
       'he is so cute', 'How dare you ask that',
       'do you want to join me for dinner ', 'I said yes',
       'she is 

In [5]:
Y_train

array([3, 2, 3, 0, 4, 0, 3, 2, 3, 1, 3, 3, 1, 3, 2, 3, 2, 3, 1, 2, 3, 0,
       2, 2, 2, 1, 4, 2, 2, 4, 0, 3, 4, 2, 0, 3, 2, 2, 3, 4, 2, 2, 0, 2,
       3, 0, 3, 2, 4, 3, 0, 3, 3, 3, 4, 2, 1, 1, 1, 2, 3, 1, 0, 0, 0, 3,
       4, 4, 2, 2, 1, 2, 0, 3, 2, 2, 0, 0, 3, 1, 2, 1, 2, 2, 4, 3, 3, 2,
       4, 0, 0, 0, 3, 3, 3, 2, 0, 1, 2, 3, 0, 2, 2, 2, 3, 2, 2, 2, 4, 1,
       1, 3, 3, 4, 1, 2, 1, 1, 3, 1, 0, 4, 0, 3, 3, 4, 4, 1, 4, 3, 0, 2])

In [6]:
X_train[5] , Y_train[5]

('I love you mum', 0)

In [7]:
X_train[9] , Y_train[9]

('I want to go play', 1)

In [8]:
def label_to_emoji(label):
    emojies = ["💚" , "🏀" , "😄" , "😞" , "🍽"]
    return emojies[label]

print(label_to_emoji(0))
print(label_to_emoji(1))
print(label_to_emoji(2))
print(label_to_emoji(3))
print(label_to_emoji(4))

💚
🏀
😄
😞
🍽


In [9]:
X_train[5] , label_to_emoji(Y_train[5])

('I love you mum', '💚')

In [10]:
unique , counts = np.unique(Y_train , return_counts=True)
print(unique)
print(counts)

[0 1 2 3 4]
[22 19 38 36 17]


In [11]:
max(X_train , key=len)

'I am so impressed by your dedication to this project'

In [12]:
len(max(X_train , key=len))

52

In [13]:
max(X_train , key=len).split()

['I',
 'am',
 'so',
 'impressed',
 'by',
 'your',
 'dedication',
 'to',
 'this',
 'project']

In [14]:
max_sentence_len = len(max(X_train , key=len).split(" "))
max_sentence_len

10

In [15]:
!wget https://nlp.stanford.edu/data/glove.6B.zip

# OR :
# import requests
# url = r'https://nlp.stanford.edu/data/glove.6B.zip'
# output = r'./glove.6B.zip'
# r = requests.get(url)
# with open(output, 'wb') as f:
#     f.write(r.content)

--2024-01-15 13:59:35--  https://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2024-01-15 13:59:36--  https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glove.6B.zip        100%[===================>] 822.24M  5.01MB/s    in 2m 39s  

2024-01-15 14:02:15 (5.17 MB/s) - ‘glove.6B.zip’ saved [862182613/862182613]



In [16]:
!unzip -q glove.6B.zip -d glove.6B

### the dictionary we want to create :
{
"hello" : [ 0.46529 , -0.22325 , -0.49207 ,  0.33727 , ... ] , <br/>
  "book" : [-1.0178  ,  0.68267 , -0.20788 , -0.73393 ,  1.2597  ... ] , <br/>
  ....

}


In [ ]:
text_file = open("/content/glove.6B/glove.6B.50d.txt" , encoding="utf-8")

word_vectors = {}
for line in text_file :
  line = line.strip().split()
  print(line)
  word = line[0]
  #print(word)
  vector = np.array(line[1:] , dtype=np.float64)
  #print(vector)
  word_vectors[word] = vector


In [35]:
word_vectors["snake"]

array([ 0.49251 , -0.24279 , -0.49748 ,  0.28443 ,  0.16984 ,  0.61016 ,
        0.20294 , -0.19734 ,  0.93474 , -0.11809 , -0.26342 ,  0.97142 ,
        1.0427  ,  0.60017 , -0.46936 ,  0.10087 ,  0.60649 ,  1.1277  ,
       -1.1823  , -0.29334 , -0.72885 , -0.46904 ,  1.1104  ,  0.27504 ,
        0.48043 , -1.3031  , -0.58713 ,  0.90264 ,  0.089552, -0.60348 ,
        1.1117  , -0.85367 , -0.13902 ,  0.87767 , -0.19307 ,  0.10299 ,
       -0.83688 , -0.87202 ,  0.46529 , -0.22325 , -0.49207 ,  0.33727 ,
       -0.49699 ,  0.95006 ,  0.75007 , -0.21252 ,  0.47244 , -1.4552  ,
        0.11704 , -0.61483 ])

In [36]:
word_vectors["iran"]

array([-0.18997  ,  0.11493  ,  0.85566  , -0.039811 ,  0.10742  ,
       -0.44042  ,  1.2496   ,  0.49928  ,  0.58689  ,  0.8321   ,
        0.027948 , -0.85445  , -0.39854  , -0.18763  , -0.050099 ,
        0.95036  ,  0.59861  ,  0.25454  ,  0.6548   ,  0.87505  ,
        0.82139  , -0.0041283,  0.9193   , -0.033385 ,  0.1914   ,
       -3.0393   ,  0.58703  ,  0.23673  ,  0.031058 ,  0.17775  ,
        2.4503   , -0.35655  , -0.68777  , -0.43984  ,  0.12271  ,
       -0.46345  , -0.29642  ,  0.33648  , -1.6442   ,  0.23183  ,
       -0.019779 ,  0.0057172,  0.94701  , -1.2708   ,  0.53767  ,
        0.80297  , -0.70422  ,  1.7059   , -0.64729  , -0.97299  ])

In [37]:
word_vectors["python"]

array([ 0.5897  , -0.55043 , -1.0106  ,  0.41226 ,  0.57348 ,  0.23464 ,
       -0.35773 , -1.78    ,  0.10745 ,  0.74913 ,  0.45013 ,  1.0351  ,
        0.48348 ,  0.47954 ,  0.51908 , -0.15053 ,  0.32474 ,  1.0789  ,
       -0.90894 ,  0.42943 , -0.56388 ,  0.69961 ,  0.13501 ,  0.16557 ,
       -0.063592,  0.35435 ,  0.42819 ,  0.1536  , -0.47018 , -1.0935  ,
        1.361   , -0.80821 , -0.674   ,  1.2606  ,  0.29554 ,  1.0835  ,
        0.2444  , -1.1877  , -0.60203 , -0.068315,  0.66256 ,  0.45336 ,
       -1.0178  ,  0.68267 , -0.20788 , -0.73393 ,  1.2597  ,  0.15425 ,
       -0.93256 , -0.15025 ])

In [38]:
word_vectors["kiana"]

array([ 0.031918, -0.44988 ,  0.2117  , -0.24515 , -0.55618 ,  0.72347 ,
        0.43707 ,  0.39521 ,  0.35605 , -0.50786 , -0.50423 , -0.1079  ,
       -0.14377 , -0.25872 , -0.18964 , -0.14668 , -0.22247 ,  0.34439 ,
        0.69779 , -0.42618 , -0.61677 ,  0.83128 , -0.23124 , -0.060008,
        0.93573 ,  0.67213 , -0.28688 ,  0.28456 , -0.45824 ,  0.17432 ,
       -1.54    ,  0.42625 ,  0.12369 ,  0.73562 , -0.17367 ,  0.12393 ,
       -0.073008,  0.056451,  0.47745 , -0.28937 ,  0.63418 ,  0.38361 ,
       -0.50057 , -0.027956, -0.53396 ,  0.047757,  0.43252 ,  0.21063 ,
       -0.15044 ,  0.48666 ])

In [39]:
len(word_vectors["you"])

50

# length of all word's feature vectors , in glove.6B.50d.txt is equal to 50 .

### Each word , has it's own feature vector

<br/>

# Question :    
how to feed a sentence with many words , into a network ?
<br/>
or
<br/>
### how to feed many feature vectors with  length of 50 , into our network ?

<br/>

1st idea : concat these FV's :    
## problem :  
here we have a Fvector of lenght 150 (for a sentence with 3 words) , THERFORE we have to consider 150 neurons in input layers . <br/>
which is not compatible with other sentence's length .
and this network only works with sentences with 3 words .

<br/>

# solution  :  
take MEAN(average) of all N Feature vectors .
so the result's length will be 50 .



we implement this idea on our X_train data :

In [40]:
# first he have to convert uppercase alphabets in X_train words

def sentence_to_average(sentence):
  sentence= sentence.lower()
  words = sentence.strip().split(" ")

  sum_vectors = np.zeros((50,))
  for word in words :
      sum_vectors += word_vectors[word]

  avg_vector = sum_vectors / len(words)
  return avg_vector


sentence_to_average("i hate fish")


array([-0.15917333, -0.10315333, -0.346679  , -0.46174667,  0.49464   ,
        0.10710667, -0.26262   , -0.03155247,  0.05453667,  0.12203586,
       -0.22185333,  0.54613   ,  0.19048333, -0.14560667,  0.90449   ,
        0.0391347 ,  0.56057   ,  0.11737533, -0.335168  , -0.56153   ,
       -0.40509   , -0.04400667,  1.00475   ,  0.51751   ,  0.67369667,
       -1.72456   , -0.63001   ,  0.241895  ,  1.16233333, -0.96878   ,
        2.5002    ,  0.35573667, -0.24802333, -0.09538333, -0.54016967,
       -0.13841   , -0.03611667, -0.07173667,  0.31141   , -0.10284333,
       -0.09298877,  0.00746733,  0.31971   ,  0.51315333,  0.69481533,
        0.30034   , -0.24001667, -0.51085333, -0.051172  ,  0.50552   ])

In [41]:
X_train_avg = []
for x_train in X_train :
  X_train_avg.append(sentence_to_average(x_train))

X_train_avg = np.array(X_train_avg)
X_train_avg.shape

(132, 50)

In [42]:
Y_train

array([3, 2, 3, 0, 4, 0, 3, 2, 3, 1, 3, 3, 1, 3, 2, 3, 2, 3, 1, 2, 3, 0,
       2, 2, 2, 1, 4, 2, 2, 4, 0, 3, 4, 2, 0, 3, 2, 2, 3, 4, 2, 2, 0, 2,
       3, 0, 3, 2, 4, 3, 0, 3, 3, 3, 4, 2, 1, 1, 1, 2, 3, 1, 0, 0, 0, 3,
       4, 4, 2, 2, 1, 2, 0, 3, 2, 2, 0, 0, 3, 1, 2, 1, 2, 2, 4, 3, 3, 2,
       4, 0, 0, 0, 3, 3, 3, 2, 0, 1, 2, 3, 0, 2, 2, 2, 3, 2, 2, 2, 4, 1,
       1, 3, 3, 4, 1, 2, 1, 1, 3, 1, 0, 4, 0, 3, 3, 4, 4, 1, 4, 3, 0, 2])

In [43]:
# we have 5 neurons in last layer of network

# we should one-hot Y outputs
Y_train_OneHot = tf.keras.utils.to_categorical(Y_train , num_classes=5)
Y_train_OneHot

array([[0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [1., 0.

# TRAIN

In [49]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(5 , input_shape=(50,) , activation="softmax")
])

model.compile(optimizer=tf.keras.optimizers.Adam() ,
              loss=tf.keras.losses.categorical_crossentropy,
              metrics="accuracy")

model.fit(X_train_avg , Y_train_OneHot , epochs=450)

Epoch 1/450
5/5 [==============================] - 0s 4ms/step - loss: 1.9347 - accuracy: 0.1894
Epoch 2/450
5/5 [==============================] - 0s 3ms/step - loss: 1.8895 - accuracy: 0.1894
Epoch 3/450
5/5 [==============================] - 0s 3ms/step - loss: 1.8505 - accuracy: 0.2045
Epoch 4/450
5/5 [==============================] - 0s 3ms/step - loss: 1.8097 - accuracy: 0.1970
Epoch 5/450
5/5 [==============================] - 0s 3ms/step - loss: 1.7723 - accuracy: 0.2197
Epoch 6/450
5/5 [==============================] - 0s 3ms/step - loss: 1.7369 - accuracy: 0.2424
Epoch 7/450
5/5 [==============================] - 0s 3ms/step - loss: 1.7083 - accuracy: 0.2273
Epoch 8/450
5/5 [==============================] - 0s 3ms/step - loss: 1.6802 - accuracy: 0.2197
Epoch 9/450
5/5 [==============================] - 0s 4ms/step - loss: 1.6531 - accuracy: 0.2424
Epoch 10/450
5/5 [==============================] - 0s 3ms/step - loss: 1.6285 - accuracy: 0.2652
Epoch 11/450
5/5 [===========

# TEST

In [54]:
my_test = "i hate eating fish"

# extracting features
my_test_avg = sentence_to_average(my_test)
my_test_avg

array([ 0.0130675 , -0.16553   , -0.59810925, -0.49592   ,  0.59033   ,
        0.22704   , -0.32189   , -0.12010185,  0.222575  ,  0.11118689,
       -0.2046    ,  0.44136   ,  0.3844075 , -0.02622   ,  0.9114375 ,
        0.10927853,  0.3785775 ,  0.2093365 , -0.343201  , -0.52781   ,
       -0.26966   , -0.03548105,  1.1430625 ,  0.5685    ,  0.60376   ,
       -1.471715  , -0.5846825 ,  0.28988625,  1.222875  , -0.723584  ,
        2.4087    ,  0.490035  , -0.215285  ,  0.00643   , -0.49763225,
       -0.0170525 , -0.1293525 ,  0.191065  ,  0.431245  ,  0.0333175 ,
       -0.24118657, -0.057487  ,  0.20188   ,  0.715315  ,  1.0069615 ,
        0.3474925 , -0.2268875 , -0.5768925 ,  0.114906  ,  0.533535  ])

In [55]:
my_test_avg = np.array([my_test_avg])
result = model.predict(my_test_avg)
y_pred = np.argmax(result)
label_to_emoji(y_pred)

1/1 [==============================] - 0s 18ms/step


'🍽'